$schema: vscode://schemas/color-theme
author: Kyle Denton
name: Artemis
colorSpaceName: sRGB
semanticClass: theme.dark.artemis_syntax
tokenColors:

# https://macromates.com/manual/en/language_grammars

# -----------------------------------------------------------------------------
# Comment
# -----------------------------------------------------------------------------

# Generic <comment> matches
- scope:
  - comment
  settings:
    foreground: _mono-3
    fontStyle: italic

# -----------------------------------------------------------------------------
# Constant
# -----------------------------------------------------------------------------

- scope:
  - constant
  settings:
    foreground: _whiskey-orange

# -----------------------------------------------------------------------------
# Entity
# -----------------------------------------------------------------------------

# Generic entity
- scope:
  - entity
  settings:
    foreground: _froly-red

# Other entities
- scope:
  - entity.other
  settings:
    foreground: _whiskey-orange

# Function names
- scope:
  - entity.name.function
  settings:
    foreground: _cornflower-blue

# Class and inherited class names
- scope:
  - entity.name.type
  - entity.other.inherited-class
  settings:
    foreground: _corvette-orange


# -----------------------------------------------------------------------------
# Invalid
# -----------------------------------------------------------------------------

- scope:
  - invalid
  settings:
    foreground: _corvette-orange

# -----------------------------------------------------------------------------
# Keyword
# -----------------------------------------------------------------------------

# Generic <keyword> matches
- scope:
  - keyword
  - keyword.operator
  settings:
    foreground: _orchid-purple

# Generic Units
- scope:
  - keyword.other.unit
  settings:
    foreground: _whiskey-orange

# -----------------------------------------------------------------------------
# Markup
# -----------------------------------------------------------------------------

# Generic <markup> matches
# - scope:
#   - markup
#   settings:
#     foreground: _pink

# -----------------------------------------------------------------------------
# Meta
# -----------------------------------------------------------------------------

# Generic <meta> matches
- scope:
  - meta
  settings:
    foreground: _mono-1

- scope:
  - meta.object-literal.key
  settings:
    foreground: _froly-red

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------

# Generic <storage> matches
- scope:
  - storage
  settings:
    foreground: _orchid-purple

# -----------------------------------------------------------------------------
# String
# -----------------------------------------------------------------------------

# Generic string match
- scope:
  - string
  settings:
    foreground: _olivine-green


# -----------------------------------------------------------------------------
# Support
# -----------------------------------------------------------------------------

# Generic support match
- scope:
  - support
  settings:
    foreground: _froly-red

# Matches a Class reference when referenced later
- scope:
  - support.class
  settings:
    foreground: _corvette-orange

# CSS property declarations
- scope:
  - support.type.property-name
  settings:
    foreground: _mono-1

# CSS property values
- scope:
  - support.constant.property-value
  settings:
    foreground: _olivine-green

# CSS functions
- scope:
  - support.function.misc
  settings:
    foreground: _viking-blue


# -----------------------------------------------------------------------------
# Variable
# -----------------------------------------------------------------------------

# Generic <variable> matches
- scope:
  - variable
  - variable.parameter
  settings:
    foreground: _mono-1

- scope:
  - variable.other.property
  - variable.other.object.property
  - variable.prop
  - variable.argument
  settings:
    foreground: _froly-red

# -----------------------------------------------------------------------------
# Punctuation
# -----------------------------------------------------------------------------

- scope:
  - punctuation.definition.tag
  - punctuation.separator
  settings:
    foreground: _orchid-purple

